nelmio_cors:
    #Section default ce qui s'applique aux routes si aucune config n'est définie dans PATH
    defaults:
        # autorise tous les sous-domaine (ex: https://.*.exemple.com')
        origin_regex: true
        # variable d'environnement (on autorise tout dans un premier temps)
        allow_origin: ['*']
        # on autorise le frontend Angular
        # liste des méthodes HTTP autorisées pour les requêtes cross-origin
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # Ce que le front peut envoyer (content-type pour les JSON, forumlaires... authorisation pour les token)
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        # Temps en seconde pendant lequel le navigateur met en cache la politique CORS
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
            max_age: 3600
